package com.free.mybatis.mapper;

import com.free.mybatis.pojo.Dept2;
import java.util.List;

public interface Dept2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Wed Aug 23 23:20:57 CST 2023
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Wed Aug 23 23:20:57 CST 2023
     */
    int insert(Dept2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Wed Aug 23 23:20:57 CST 2023
     */
    Dept2 selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Wed Aug 23 23:20:57 CST 2023
     */
    List<Dept2> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Wed Aug 23 23:20:57 CST 2023
     */
    int updateByPrimaryKey(Dept2 record);
}