package com.free.mybatis.mapper;

import com.free.mybatis.pojo.Emp3;
import com.free.mybatis.pojo.Emp3Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Emp3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    int countByExample(Emp3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    int deleteByExample(Emp3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    int insert(Emp3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    int insertSelective(Emp3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    List<Emp3> selectByExample(Emp3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    Emp3 selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    int updateByExampleSelective(@Param("record") Emp3 record, @Param("example") Emp3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    int updateByExample(@Param("record") Emp3 record, @Param("example") Emp3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    int updateByPrimaryKeySelective(Emp3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Wed Aug 23 23:28:27 CST 2023
     */
    int updateByPrimaryKey(Emp3 record);
}